SELECT ?person ?personLabel ?member ?memberlabel
WHERE
{
  ?person wdt:P463 ?member;
  wdt:P31 wd:Q5. #shorthand for ?person wdt:P31 wd:Q5



  ?member wdt:P279* wd:Q123885;

  SERVICE wikibase:label {bd:serviceParam wikibase:language "en, fr, sp"}

}
