#!/bin/sh
# Brute force archive of all 1604 fellows pages, not very clever, ignores 502 Bad Gateway response from server

sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/david-neuberger-13407/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/yves-alain-barde-13377/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/tony-bell-13378/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/keith-beven-13379/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/wendy-bickmore-13380/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/neil-burgess-13382/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/krishna-chatterjee-13383/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/jonathan-gregory-13390/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/tim-elliott-13388/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/warren-east-13387/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/james-durrant-13386/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/whitfield-diffie-13385/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/max-cooper-13384/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/mark-gross-13391/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/robert-grubbs-13392/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/anne-ferguson-smith-13389/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/christopher-bishop-13381/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/roy-harrison-13393/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/gabriele-hegerl-13394/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/julia-brown-13400/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/subhash-khot-13399/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/yvonne-jones-13398/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/richard-houlston-13397/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/hideo-hosono-13396/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/edward-holmes-13395/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/stafford-lightman-13401/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/andrew-mckenzie-13403/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/marcia-mcnutt-13404/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/gerard-milburn-13405/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/gin%C3%A9s-morata-13406/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/anne-neville-13408/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/alison-noble-13409/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/andrew-orr-ewing-13410/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/david-owen-13411/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/lawrence-paulson-13412/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/josephine-pemberton-13413/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/gavin-salam-13419/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/david-rubinsztein-13418/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/robert-ritchie-13417/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/anne-ridley-13416/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/sarah-sallyprice13415/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/sandu-popescu-13414/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/angus-silver-13421/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/gordon-slade-13422/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/peter-smith-13423/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/nicola-spaldin-13424/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/jonathan-stoye-13425/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/thomas-sudhof-13426/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/susanne-von-caemmerer-13432/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/patrick-vallance-13431/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/david-tilman-13430/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/jennifer-thomas-13429/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/roy-taylor-13428/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/john-sutherland-13427/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/hugh-watkins-13433/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/susan-wessler-13434/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/roger-williams-13435/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/kenneth-wolfe-13436/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/andrew-woods-13437/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/yadvinder-malhi-13402/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/nigel-shadbolt-13420/
