
#!/bin/sh
# Brute force archive of all 1604 fellows pages, not very clever, ignores 502 Bad Gateway response from server


wget https://web.archive.org/save/https://royalsociety.org/people/jonathan-flint-14090/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/caucher-birkar-14079/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/roy-kerr-14105/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/richard-harland-14097/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/liz-sockett-14125/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/christopher-hacon-14094/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/mark-handley-14096/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/david-milstein-14110/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/leonid-sazanov-14121/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/gregory-scholes-14122/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/benjamin-blencowe-14080/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/anant-parekh-14114/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/peter-butler-14082/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/akshay-venkatesh-14133/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/julian-peto-14115/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/doug-turnbull-14132/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/christine-orengo-14112/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/david-nicholls-14111/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/barbara-sherwood-lollar-14123/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/barry-barish-14076/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/richard-jozsa-14101/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/jonathan-knight-14106/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/matthew-hurles-14100/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/gagandeep-kang-14102/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/ian-tomlinson-14131/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/yusuf-hamied-14095/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/martin-head-gordon-14099/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/andrew-taylor-14129/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/james-briscoe-14081/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/bernard-fanaroff-14089/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/gareth-mckinley-14109/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/james-rothman-14119/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/mark-mayer-14108/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/kumar-wickramasinghe-14134/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/inez-fung-14092/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/hans-clevers-14084/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/brian-staskawicz-14127/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/steve-kay-14103/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/anne-osbourn-14113/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/robert-tibshirani-14130/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/martin-embley-14088/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/charles-bangham-14075/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/akkihebbal-ravishankara-14116/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/john-rodenburg-14118/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/jack-szostak-14128/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/paraskevas-sphicas-14126/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/peter-haynes-14098/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/caetano-reis-e-sousa-14117/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/marta-kwiatkowska-14107/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/sandra-diaz-14086/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/lucy-carpenter-14083/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/john-michael-kendall-14104/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/elaine-fuchs-14091/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/molly-shoichet-14124/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/gurdyal-besra-14077/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/jack-dongarra-14087/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/matthew-rushworth-14120/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/salim-abdool-karim-14074/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/sarah-darby-14073/
sleep 3
wget https://web.archive.org/save/https://royalsociety.org/people/george-davey-smith-14085/
