#!/bin/sh
# Brute force archive of all 1604 fellows pages, not very clever, ignores 502 Bad Gateway response from server

wget https://royalsociety.org/people/polly-arnold-13795/
sleep 3
wget https://royalsociety.org/people/jim-al-khalili-13796/
sleep 3
wget https://royalsociety.org/people/timothy-softley-13845/
sleep 3
wget https://royalsociety.org/people/john-speakman-13846/
sleep 3
wget https://royalsociety.org/people/david-richardson-13837/
sleep 3
wget https://royalsociety.org/people/tracy-palmer-13832/
sleep 3
wget https://royalsociety.org/people/geordie-williamson-13853/
sleep 3
wget https://royalsociety.org/people/guy-wilkinson-13852/
sleep 3
wget https://royalsociety.org/people/dominic-kwiatkowski-13825/
sleep 3
wget https://royalsociety.org/people/andrew-king-13823/
sleep 3
wget https://royalsociety.org/people/catherine-martin-13827/
sleep 3
wget https://royalsociety.org/people/lalita-ramakrishnan-13835/
sleep 3
wget https://royalsociety.org/people/fabiola-gianotti-13813/
sleep 3
wget https://royalsociety.org/people/gregory-edgecombe-13810/
sleep 3
wget https://royalsociety.org/people/peter-dayan-13807/
sleep 3
wget https://royalsociety.org/people/neil-brockdorff-13800/
sleep 3
wget https://royalsociety.org/people/carolyn-bertozzi-13798/
sleep 3
wget https://royalsociety.org/people/gregory-hannon-13816/
sleep 3
wget https://royalsociety.org/people/vincenzo-cerundolo-13802/
sleep 3
wget https://royalsociety.org/people/francesco-caruso-13801/
sleep 3
wget https://royalsociety.org/people/margaret-brimble-13799/
sleep 3
wget https://royalsociety.org/people/jillian-banfield-13797/
sleep 3
wget https://royalsociety.org/people/judy-hirst-13818/
sleep 3
wget https://royalsociety.org/people/demis-hassabis-13817/
sleep 3
wget https://royalsociety.org/people/kevin-costello-13804/
sleep 3
wget https://royalsociety.org/people/angela-strank-13848/
sleep 3
wget https://royalsociety.org/people/sebsebe-demissew-13808/
sleep 3
wget https://royalsociety.org/people/richard-dixon-13809/
sleep 3
wget https://royalsociety.org/people/jeffrey-friedman-13812/
sleep 3
wget https://royalsociety.org/people/roger-goody-13814/
sleep 3
wget https://royalsociety.org/people/vassilis-pachnis-13831/
sleep 3
wget https://royalsociety.org/people/peterohearn13830/
sleep 3
wget https://royalsociety.org/people/richard-marais-13828/
sleep 3
wget https://royalsociety.org/people/butler-lampson-13826/
sleep 3
wget https://royalsociety.org/people/dimitri-kullmann-13824/
sleep 3
wget https://royalsociety.org/people/graeme-jameson-13820/
sleep 3
wget https://royalsociety.org/people/tullio-pozzan-13833/
sleep 3
wget https://royalsociety.org/people/nancy-reid-13836/
sleep 3
wget https://royalsociety.org/people/graham-richards-13838/
sleep 3
wget https://royalsociety.org/people/sheila-rowan-13839/
sleep 3
wget https://royalsociety.org/people/ingrid-scheffer-13841/
sleep 3
wget https://royalsociety.org/people/michelle-simmons-13843/
sleep 3
wget https://royalsociety.org/people/alexander-dawid-13806/
sleep 3
wget https://royalsociety.org/people/nikolay-zheludev-13855/
sleep 3
wget https://royalsociety.org/people/daniel-wise-13854/
sleep 3
wget https://royalsociety.org/people/charles-swanton-13849/
sleep 3
wget https://royalsociety.org/people/graeme-stephens-13847/
sleep 3
wget https://royalsociety.org/people/john-smol-13844/
sleep 3
wget https://royalsociety.org/people/albrecht-hofmann-13819/
sleep 3
wget https://royalsociety.org/people/sophien-kamoun-13822/
sleep 3
wget https://royalsociety.org/people/ian-prentice-13834/
sleep 3
wget https://royalsociety.org/people/martin-chalfie-13803/
sleep 3
wget https://royalsociety.org/people/robert-crabtree-13805/
sleep 3
wget https://royalsociety.org/people/wenfei-fan-13811/
sleep 3
wget https://royalsociety.org/people/robin-grimes-13815/
sleep 3
wget https://royalsociety.org/people/david-willetts-13851/
sleep 3
wget https://royalsociety.org/people/peter-visscher-13850/
sleep 3
wget https://royalsociety.org/people/adi-shamir-13842/
sleep 3
wget https://royalsociety.org/people/joachim-sauer-13840/
sleep 3
wget https://royalsociety.org/people/elon-musk-13829/
sleep 3
wget https://royalsociety.org/people/harren-jhoti-13821/
